// <auto-generated />
using ApiWeb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiWeb.Migrations
{
    [DbContext(typeof(CreateContextModel))]
    [Migration("20190714141329_Initial1")]
    partial class Initial1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApiWeb.Models.Animals", b =>
                {
                    b.Property<int>("Id_animal")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("id_color_leather");

                    b.HasKey("Id_animal");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("ApiWeb.Models.Leather", b =>
                {
                    b.Property<int>("Id_leather")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id_leather");

                    b.ToTable("Leathers");
                });

            modelBuilder.Entity("ApiWeb.Models.Location", b =>
                {
                    b.Property<int>("Id_location")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id_location");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("ApiWeb.Models.Region", b =>
                {
                    b.Property<int>("Id_region")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id_region");

                    b.ToTable("Regions");
                });
#pragma warning restore 612, 618
        }
    }
}
