// <auto-generated />
using System;
using ApiWeb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiWeb.Migrations
{
    [DbContext(typeof(CreateContextModel))]
    partial class CreateContextModelModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApiWeb.Models.Animals", b =>
                {
                    b.Property<int>("Id_animal")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("LeatherId_leather");

                    b.Property<int?>("LocationId_location");

                    b.Property<string>("Name");

                    b.HasKey("Id_animal");

                    b.HasIndex("LeatherId_leather");

                    b.HasIndex("LocationId_location");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("ApiWeb.Models.Leather", b =>
                {
                    b.Property<int>("Id_leather")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id_leather");

                    b.ToTable("Leathers");
                });

            modelBuilder.Entity("ApiWeb.Models.Location", b =>
                {
                    b.Property<int>("Id_location")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int?>("RegionId_region");

                    b.HasKey("Id_location");

                    b.HasIndex("RegionId_region");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("ApiWeb.Models.Region", b =>
                {
                    b.Property<int>("Id_region")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id_region");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("ApiWeb.Models.Animals", b =>
                {
                    b.HasOne("ApiWeb.Models.Leather", "Leather")
                        .WithMany()
                        .HasForeignKey("LeatherId_leather");

                    b.HasOne("ApiWeb.Models.Location", "Location")
                        .WithMany("Animals")
                        .HasForeignKey("LocationId_location");
                });

            modelBuilder.Entity("ApiWeb.Models.Location", b =>
                {
                    b.HasOne("ApiWeb.Models.Region", "Region")
                        .WithMany("Locations")
                        .HasForeignKey("RegionId_region");
                });
#pragma warning restore 612, 618
        }
    }
}
